server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: tripshare
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/tripshare
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/changelog/change-log-master.xml
    enabled: false
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
  #    password: redispw
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092