version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: tripshare-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - mynetwork
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#    volumes:
#      - /data:/data
#    networks:
#      - mynetwork
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "test:1:1"
#    volumes:
#      - /kafka/data:/kafka/data
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - zookeeper
#    networks:
#      - mynetwork
networks:
  mynetwork:
    driver: bridge